spring:
  profiles:
    active: local

server:
  port: 8080

application:
  role: "ALL"
  version: "Api Tester v2.0.0"

datasource:
  driver-class-name:
  url:
  username:
  password:

postgresql:
  filepath: